import { ActivosFamilia } from './activosfamilia';
import { ActivosNegocio } from './activosnegocio';
import { Creditos } from './creditos';
import { Inventario } from './inventario';
import { Inversiones } from './inversiones';
import { Pasivos } from './pasivos';
import { Proveedores } from './proveedores';
import { Recuperacion } from './recuperacion';

export class Balance {
    efectivo: string;
    clienteCobrar: string;
    observacionesCobrar: string;
    valorCobrar: string;
    incobrableCobrar: string;
    recuperacionCobrar: string;
    cobrarTotal: string;
    porcentajeCobrar: number;
    recuperacion:Recuperacion[];
    totalRecuperacion:number;
    inventarioRow: Inventario[];
    inventarioTotal: number;
    activosFamRows: ActivosFamilia[];
    actfamTotal: number;
    actividadNegRows: ActivosNegocio[];
    actnegTotal: number;
    proveedoresRow:Proveedores[];
    proveedoresTotal:number;
    creditoactual:boolean;
    creditos: Creditos[];
    totalCreditos: string;
    aplicaInversiones:boolean;
    inversiones:Inversiones[];
    totalInversiones:number;
    pasivosRows: Pasivos[];
    tcuotaf: string;
    tcorrientef: string;
    tnocorrientef: string;
    tcuotan: string;
    tcorrienten: string;
    tnocorrienten: string;
}